### ISSUE TITLE
无法生成总结 

### ISSUE THREAD

**Issue by Nothingness-Void** [mgsky1/FG#7]
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "E:\bot\FG\cn\acmsmu\FG\DailyConclusion.py", line 94, in __generateWC
    wc.to_file(os.path.join(os.getcwd(),'cn','acmsmu','FG','data','assets','wc',figName))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\wordcloud\wordcloud.py", line 706, in to_file
    img.save(filename, optimize=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 2131, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\bot\\FG\\cn\\acmsmu\\FG\\data\\assets\\wc\\2021-01-1923-10-08-58.png'
Executing <Task pending name='Task-19' coro=<run_coroutine_job() running at C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base_py3.py:29> cb=[AsyncIOExecutor._do_submit_job.<locals>.callback() at C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\asyncio.py:39] created at C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\asyncio.py:51> took 8.171 seconds

可以看出结巴分词还有算法中的连成文章部分成功了 但是WC生成失败了

**Comment by mgsky1** [comment]
确认一下E:\bot\FG\cn\acmsmu\FG\data\assets\wc这个路径是否存在

**Comment by Nothingness-Void** [comment]
没有wc这个文件夹 我以为会自己创建来着 我再去试试
